# Generated by Django 4.0.4 on 2022-10-07 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('user_auth', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user_phone', models.CharField(max_length=20, null=True)),
                ('user_phone_country_code', models.CharField(default='+1', max_length=8)),
                ('sms_number', models.IntegerField(blank=True, null=True)),
                ('login_state', models.CharField(choices=[('phone_verification_pending', 'phone_verification_pending'), ('logged_in', 'logged_in'), ('logged_out', 'logged_out')], default='phone_verification_pending', max_length=100)),
                ('device_id', models.BooleanField(default=False)),
                ('user_device_id', models.CharField(max_length=400, null=True)),
                ('name_page_done', models.BooleanField(default=False)),
                ('location_page_done', models.BooleanField(default=False)),
                ('cold_start_done', models.BooleanField(default=False)),
                ('firebase_token', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
